// Generates src/generated/ from the vendored contract: TypeScript types from the published JSON Schemas
// (json-schema-to-typescript), and the schemas and contract data the assembler embeds.
// Usage: node scripts/generate.mjs [--check]. With --check it writes nothing and fails when a file is stale.
import { mkdirSync, readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const VENDOR = join(ROOT, 'vendor', 'cwa');
const OUT = join(ROOT, 'src', 'generated');
const BASE = 'https://contextwindowarchitecture.io/schema/';
const BANNER = '// Generated by scripts/generate.mjs from vendor/cwa/. Do not edit; run pnpm run generate.\n';
const read = path => JSON.parse(readFileSync(join(VENDOR, path), 'utf8'));

const schemaFiles = readdirSync(join(VENDOR, 'schema')).filter(name => name.endsWith('.schema.json')).sort();
const schemas = Object.fromEntries(schemaFiles.map(name => [name, read(join('schema', name))]));

// One wrapper schema references every published schema, so a type shared through $ref is declared once.
// $refs resolve against the schemas' $id and are served from the vendored files, never fetched.
const wrapper = {
  title: 'CwaContract',
  description: 'Every published schema; this wrapper exists only to generate the types once.',
  type: 'object',
  additionalProperties: false,
  properties: Object.fromEntries(schemaFiles.map(name => [name.replace('.schema.json', ''), { $ref: BASE + name }])),
};
const types = await compile(wrapper, 'CwaContract', {
  bannerComment: BANNER.trim(),
  additionalProperties: false,
  strictIndexSignatures: true,
  ignoreMinAndMaxItems: true,
  format: true,
  $refOptions: {
    resolve: {
      http: false,
      vendored: {
        order: 1,
        canRead: file => file.url.startsWith(BASE),
        read: file => readFileSync(join(VENDOR, 'schema', file.url.slice(BASE.length).split('#')[0]), 'utf8'),
      },
    },
  },
});

const reasons = read('contract/reasons.json');
const slotDefaults = read('contract/slot-defaults.json');
const lock = JSON.parse(readFileSync(join(ROOT, 'vendor', 'cwa.lock.json'), 'utf8'));
const json = value => JSON.stringify(value, null, 2);
const contract = `${BANNER}
/** The website commit the vendored contract came from (vendor/cwa.lock.json). */
export const CONTRACT_SOURCE = ${json({ website_commit: lock.website_commit, dirty: lock.dirty })} as const;

/** The published JSON Schemas, keyed by file name (vendor/cwa/schema/). */
export const SCHEMAS: Readonly<Record<string, Record<string, unknown>>> = ${json(schemas)};

/** contract/reasons.json: exclusion and refusal codes, in the order R-21 ranks them. */
export const REASONS = ${json(reasons)} as const;

/** contract/slot-defaults.json: each slot's authority, tier and policy-field defaults (R-3). */
export const SLOT_DEFAULTS = ${json(slotDefaults)} as const;
`;

const outputs = { 'types.ts': types, 'contract.ts': contract };
if (process.argv.includes('--check')) {
  const stale = Object.entries(outputs).filter(([name, text]) =>
    !existsSync(join(OUT, name)) || readFileSync(join(OUT, name), 'utf8') !== text).map(([name]) => name);
  if (stale.length) {
    console.error(`src/generated is stale: ${stale.join(', ')}. Run pnpm run generate.`);
    process.exit(1);
  }
} else {
  mkdirSync(OUT, { recursive: true });
  for (const [name, text] of Object.entries(outputs)) writeFileSync(join(OUT, name), text);
  console.log(`generated ${Object.keys(outputs).map(name => 'src/generated/' + name).join(', ')}`);
}
